github:
  client:
    id: Ov23liO8Ca6R78HtYa0U
    secret: 37fd4d8254de51ea8eb7e8a09059c8f143794460

server:
  servlet:
    session:
      timeout: 32400 # 9시간 (초 단위)

jwt:
  secret-key: NZfLZ8BH1LqDVTzMoRN8Kd6uGv5FSu4oBjc5VeT7VtMKHgr/NeETzwxL0awVkgJWejbL6j1RxYLcFVPklnQBmA==
  expiration-time: 86400000 # 1 day (milliseconds)